@baseGraphUri = https://graph.microsoft.com/beta
@groupId = d20a418e-a00f-47a5-a8ed-e12a9d98f83a


### Get the current members of the security group
GET {{baseGraphUri}}/groups/{{groupId}}/members HTTP/1.1
Authorization: Bearer 123...

### Find the detected app
GET {{baseGraphUri}}/deviceManagement/detectedApps?$filter=(displayname, 'notepad++') HTTP/1.1
Authorization: Bearer 123...

### Get the devices from the detected app
GET {{baseGraphUri}}/deviceManagement/detectedApps/{{detectedAppID}}/managedDevices HTTP/1.1
Authorization: Bearer 123...

# Iterate through each device and get the data we need:
### Intune Device
GET {{baseGraphUri}}/deviceManagement/detectedApps/{{detectedAppID}}/managedDevices/{{IntuneID}} HTTP/1.1
Authorization: Bearer 123...

### AAD Device ID
GET {{baseGraphUri}}/devices?$filter=(deviceId eq '{{IntuneDeviceAadDeviceId}}') HTTP/1.1
Authorization: Bearer 123...

# Now we have all the data. do the logic
### Add to group
POST {{baseGraphUri}}/groups/{{groupId}}/members/$ref HTTP/1.1
Authorization: Bearer 123...

{
    "@odata.id": "$baseGraphUri/directoryObjects/{{AADDeviceID}})" 
}

### OR Delete from group
DELETE {{baseGraphUri}}/groups/{{groupId}}/members/{{AADDeviceId}}/$ref HTTP/1.1
Authorization: Bearer 123..